### ISSUE TITLE
Some chairs, taburets and bar stools are not craftable.

### ISSUE THREAD

**Issue by quiqueck** [paulevsGitch/BetterNether#440]
Reported on Discord.

Seems to affect Mushroom, Mushroom Fir and all vanilla woods

**Comment by quiqueck** [comment]
Fixed in 5.3.9

**Comment by Necrontyrr** [comment]
I wanted to note that the following items are still not craftable:

- Mushroom Fir Planks
- Mushroom Fir Stairs
- Mushroom Fir Slab
- Mushroom Fir Fence
- Mushroom Fir Gate
- Mushroom Fir Button
- Mushroom Fir Plate
- Mushroom Fir Trapdoor
- Mushroom Fir Door
- Mushroom Fir Ladder
- Mushroom Fir Sign
- Stripped Mushroom Fir Log
- Stripped Mushroom Fir Bark (this even has the wrong name block.betternether.mushroom_fir_stripped_bark)
- Mushroom Fir Wood
- Mushroom Fir Chest
- Mushroom Fir Barrel
- Mushroom Fir Crafting Table
- Reeds Stool
- Reeds Chair
- Reeds Bar Stool
- Reeds Roof Tile
- Reeds Roof Tile Stairs
- Reeds Roof Tile Slab

**Comment by quiqueck** [comment]
Oh, thanks for reporting!

**Comment by Necrontyrr** [comment]
Everything is fine now, can confirm 👍

**Comment by quiqueck** [comment]
Thanks again for reporting :)
